// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ohlc.proto

#include "ohlc.pb.h"
#include "ohlc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace OHLCService {

static const char* OHLCServer_method_names[] = {
  "/OHLCService.OHLCServer/GetOHLCsByStock",
};

std::unique_ptr< OHLCServer::Stub> OHLCServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OHLCServer::Stub> stub(new OHLCServer::Stub(channel, options));
  return stub;
}

OHLCServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetOHLCsByStock_(OHLCServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OHLCServer::Stub::GetOHLCsByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::OHLCService::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::OHLCService::Request, ::OHLCService::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOHLCsByStock_, context, request, response);
}

void OHLCServer::Stub::async::GetOHLCsByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::OHLCService::Request, ::OHLCService::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOHLCsByStock_, context, request, response, std::move(f));
}

void OHLCServer::Stub::async::GetOHLCsByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOHLCsByStock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::OHLCService::Response>* OHLCServer::Stub::PrepareAsyncGetOHLCsByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::OHLCService::Response, ::OHLCService::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOHLCsByStock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::OHLCService::Response>* OHLCServer::Stub::AsyncGetOHLCsByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOHLCsByStockRaw(context, request, cq);
  result->StartCall();
  return result;
}

OHLCServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OHLCServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OHLCServer::Service, ::OHLCService::Request, ::OHLCService::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OHLCServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::OHLCService::Request* req,
             ::OHLCService::Response* resp) {
               return service->GetOHLCsByStock(ctx, req, resp);
             }, this)));
}

OHLCServer::Service::~Service() {
}

::grpc::Status OHLCServer::Service::GetOHLCsByStock(::grpc::ServerContext* context, const ::OHLCService::Request* request, ::OHLCService::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace OHLCService

