// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ohlc.proto
#ifndef GRPC_ohlc_2eproto__INCLUDED
#define GRPC_ohlc_2eproto__INCLUDED

#include "ohlc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace OHLCService {

class OHLCServer final {
 public:
  static constexpr char const* service_full_name() {
    return "OHLCService.OHLCServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::OHLCService::OHLC* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>> AsyncGetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>>(AsyncGetOHLCByStockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>> PrepareAsyncGetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>>(PrepareAsyncGetOHLCByStockRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>* AsyncGetOHLCByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::OHLCService::OHLC>* PrepareAsyncGetOHLCByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::OHLCService::OHLC* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>> AsyncGetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>>(AsyncGetOHLCByStockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>> PrepareAsyncGetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>>(PrepareAsyncGetOHLCByStockRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response, std::function<void(::grpc::Status)>) override;
      void GetOHLCByStock(::grpc::ClientContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>* AsyncGetOHLCByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::OHLCService::OHLC>* PrepareAsyncGetOHLCByStockRaw(::grpc::ClientContext* context, const ::OHLCService::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetOHLCByStock_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetOHLCByStock(::grpc::ServerContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOHLCByStock(::grpc::ServerContext* context, ::OHLCService::Request* request, ::grpc::ServerAsyncResponseWriter< ::OHLCService::OHLC>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetOHLCByStock<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::OHLCService::Request, ::OHLCService::OHLC>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::OHLCService::Request* request, ::OHLCService::OHLC* response) { return this->GetOHLCByStock(context, request, response); }));}
    void SetMessageAllocatorFor_GetOHLCByStock(
        ::grpc::MessageAllocator< ::OHLCService::Request, ::OHLCService::OHLC>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::OHLCService::Request, ::OHLCService::OHLC>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOHLCByStock(
      ::grpc::CallbackServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetOHLCByStock<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOHLCByStock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOHLCByStock(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOHLCByStock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOHLCByStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOHLCByStock() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::OHLCService::Request, ::OHLCService::OHLC>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::OHLCService::Request, ::OHLCService::OHLC>* streamer) {
                       return this->StreamedGetOHLCByStock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOHLCByStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOHLCByStock(::grpc::ServerContext* /*context*/, const ::OHLCService::Request* /*request*/, ::OHLCService::OHLC* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOHLCByStock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::OHLCService::Request,::OHLCService::OHLC>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetOHLCByStock<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetOHLCByStock<Service > StreamedService;
};

}  // namespace OHLCService


#endif  // GRPC_ohlc_2eproto__INCLUDED
