// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ohlc.proto

#include "ohlc.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace OHLCService {

inline constexpr OHLC::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        period_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        volume_{0},
        value_{0},
        averageprice_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OHLC::OHLC(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct OHLCDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OHLCDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OHLCDefaultTypeInternal() {}
  union {
    OHLC _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OHLCDefaultTypeInternal _OHLC_default_instance_;

inline constexpr OHLCContainer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ohlcs_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OHLCContainer::OHLCContainer(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct OHLCContainerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OHLCContainerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OHLCContainerDefaultTypeInternal() {}
  union {
    OHLCContainer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OHLCContainerDefaultTypeInternal _OHLCContainer_default_instance_;
}  // namespace OHLCService
static ::_pb::Metadata file_level_metadata_ohlc_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ohlc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ohlc_2eproto = nullptr;
const ::uint32_t TableStruct_ohlc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _impl_.period_),
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _impl_.volume_),
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLC, _impl_.averageprice_),
    0,
    1,
    2,
    3,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLCContainer, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::OHLCService::OHLCContainer, _impl_.ohlcs_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::OHLCService::OHLC)},
        {16, -1, -1, sizeof(::OHLCService::OHLCContainer)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::OHLCService::_OHLC_default_instance_._instance,
    &::OHLCService::_OHLCContainer_default_instance_._instance,
};
const char descriptor_table_protodef_ohlc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nohlc.proto\022\013OHLCService\"\220\001\n\004OHLC\022\023\n\006Pe"
    "riod\030\001 \001(\tH\000\210\001\001\022\023\n\006Volume\030\002 \001(\005H\001\210\001\001\022\022\n\005"
    "Value\030\003 \001(\005H\002\210\001\001\022\031\n\014AveragePrice\030\004 \001(\001H\003"
    "\210\001\001B\t\n\007_PeriodB\t\n\007_VolumeB\010\n\006_ValueB\017\n\r_"
    "AveragePrice\"1\n\rOHLCContainer\022 \n\005OHLCs\030\001"
    " \003(\0132\021.OHLCService.OHLCb\006proto3"
};
static ::absl::once_flag descriptor_table_ohlc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ohlc_2eproto = {
    false,
    false,
    231,
    descriptor_table_protodef_ohlc_2eproto,
    "ohlc.proto",
    &descriptor_table_ohlc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ohlc_2eproto::offsets,
    file_level_metadata_ohlc_2eproto,
    file_level_enum_descriptors_ohlc_2eproto,
    file_level_service_descriptors_ohlc_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ohlc_2eproto_getter() {
  return &descriptor_table_ohlc_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ohlc_2eproto(&descriptor_table_ohlc_2eproto);
namespace OHLCService {
// ===================================================================

class OHLC::_Internal {
 public:
  using HasBits = decltype(std::declval<OHLC>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(OHLC, _impl_._has_bits_);
  static void set_has_period(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_volume(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_averageprice(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

OHLC::OHLC(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OHLCService.OHLC)
}
inline PROTOBUF_NDEBUG_INLINE OHLC::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        period_(arena, from.period_) {}

OHLC::OHLC(
    ::google::protobuf::Arena* arena,
    const OHLC& from)
    : ::google::protobuf::Message(arena) {
  OHLC* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, volume_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, volume_),
           offsetof(Impl_, averageprice_) -
               offsetof(Impl_, volume_) +
               sizeof(Impl_::averageprice_));

  // @@protoc_insertion_point(copy_constructor:OHLCService.OHLC)
}
inline PROTOBUF_NDEBUG_INLINE OHLC::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        period_(arena) {}

inline void OHLC::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, volume_),
           0,
           offsetof(Impl_, averageprice_) -
               offsetof(Impl_, volume_) +
               sizeof(Impl_::averageprice_));
}
OHLC::~OHLC() {
  // @@protoc_insertion_point(destructor:OHLCService.OHLC)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void OHLC::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.period_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void OHLC::Clear() {
// @@protoc_insertion_point(message_clear_start:OHLCService.OHLC)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.period_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000000eu) {
    ::memset(&_impl_.volume_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.averageprice_) -
        reinterpret_cast<char*>(&_impl_.volume_)) + sizeof(_impl_.averageprice_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* OHLC::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 31, 2> OHLC::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OHLC, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_OHLC_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional double AveragePrice = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0, PROTOBUF_FIELD_OFFSET(OHLC, _impl_.averageprice_)}},
    // optional string Period = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(OHLC, _impl_.period_)}},
    // optional int32 Volume = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OHLC, _impl_.volume_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(OHLC, _impl_.volume_)}},
    // optional int32 Value = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(OHLC, _impl_.value_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(OHLC, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string Period = 1;
    {PROTOBUF_FIELD_OFFSET(OHLC, _impl_.period_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 Volume = 2;
    {PROTOBUF_FIELD_OFFSET(OHLC, _impl_.volume_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 Value = 3;
    {PROTOBUF_FIELD_OFFSET(OHLC, _impl_.value_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional double AveragePrice = 4;
    {PROTOBUF_FIELD_OFFSET(OHLC, _impl_.averageprice_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\20\6\0\0\0\0\0\0"
    "OHLCService.OHLC"
    "Period"
  }},
};

::uint8_t* OHLC::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OHLCService.OHLC)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string Period = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_period();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OHLCService.OHLC.Period");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int32 Volume = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_volume(), target);
  }

  // optional int32 Value = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_value(), target);
  }

  // optional double AveragePrice = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        4, this->_internal_averageprice(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OHLCService.OHLC)
  return target;
}

::size_t OHLC::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OHLCService.OHLC)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string Period = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_period());
    }

    // optional int32 Volume = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_volume());
    }

    // optional int32 Value = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_value());
    }

    // optional double AveragePrice = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 9;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData OHLC::_class_data_ = {
    OHLC::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* OHLC::GetClassData() const {
  return &_class_data_;
}

void OHLC::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<OHLC*>(&to_msg);
  auto& from = static_cast<const OHLC&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OHLCService.OHLC)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_period(from._internal_period());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.volume_ = from._impl_.volume_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.averageprice_ = from._impl_.averageprice_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OHLC::CopyFrom(const OHLC& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OHLCService.OHLC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OHLC::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* OHLC::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void OHLC::InternalSwap(OHLC* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.period_, &other->_impl_.period_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OHLC, _impl_.averageprice_)
      + sizeof(OHLC::_impl_.averageprice_)
      - PROTOBUF_FIELD_OFFSET(OHLC, _impl_.volume_)>(
          reinterpret_cast<char*>(&_impl_.volume_),
          reinterpret_cast<char*>(&other->_impl_.volume_));
}

::google::protobuf::Metadata OHLC::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ohlc_2eproto_getter, &descriptor_table_ohlc_2eproto_once,
      file_level_metadata_ohlc_2eproto[0]);
}
// ===================================================================

class OHLCContainer::_Internal {
 public:
};

OHLCContainer::OHLCContainer(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OHLCService.OHLCContainer)
}
inline PROTOBUF_NDEBUG_INLINE OHLCContainer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : ohlcs_{visibility, arena, from.ohlcs_},
        _cached_size_{0} {}

OHLCContainer::OHLCContainer(
    ::google::protobuf::Arena* arena,
    const OHLCContainer& from)
    : ::google::protobuf::Message(arena) {
  OHLCContainer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:OHLCService.OHLCContainer)
}
inline PROTOBUF_NDEBUG_INLINE OHLCContainer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ohlcs_{visibility, arena},
        _cached_size_{0} {}

inline void OHLCContainer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OHLCContainer::~OHLCContainer() {
  // @@protoc_insertion_point(destructor:OHLCService.OHLCContainer)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void OHLCContainer::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void OHLCContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:OHLCService.OHLCContainer)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ohlcs_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* OHLCContainer::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> OHLCContainer::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_OHLCContainer_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .OHLCService.OHLC OHLCs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OHLCContainer, _impl_.ohlcs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .OHLCService.OHLC OHLCs = 1;
    {PROTOBUF_FIELD_OFFSET(OHLCContainer, _impl_.ohlcs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::OHLCService::OHLC>()},
  }}, {{
  }},
};

::uint8_t* OHLCContainer::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OHLCService.OHLCContainer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .OHLCService.OHLC OHLCs = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ohlcs_size()); i < n; i++) {
    const auto& repfield = this->_internal_ohlcs().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OHLCService.OHLCContainer)
  return target;
}

::size_t OHLCContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OHLCService.OHLCContainer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .OHLCService.OHLC OHLCs = 1;
  total_size += 1UL * this->_internal_ohlcs_size();
  for (const auto& msg : this->_internal_ohlcs()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData OHLCContainer::_class_data_ = {
    OHLCContainer::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* OHLCContainer::GetClassData() const {
  return &_class_data_;
}

void OHLCContainer::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<OHLCContainer*>(&to_msg);
  auto& from = static_cast<const OHLCContainer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OHLCService.OHLCContainer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ohlcs()->MergeFrom(
      from._internal_ohlcs());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OHLCContainer::CopyFrom(const OHLCContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OHLCService.OHLCContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool OHLCContainer::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* OHLCContainer::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void OHLCContainer::InternalSwap(OHLCContainer* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ohlcs_.InternalSwap(&other->_impl_.ohlcs_);
}

::google::protobuf::Metadata OHLCContainer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ohlc_2eproto_getter, &descriptor_table_ohlc_2eproto_once,
      file_level_metadata_ohlc_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace OHLCService
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
